### ISSUE TITLE
can't create first bug

### ISSUE THREAD

**Issue by billehunt** [ned14/BEurtle#3]
Hey,

Beurtle looks cool, but getting errors. I'm using Windows 8, Tortoise Git (latest ver) and latest ver of Beurtle (1.50 alpha2).
a) in commit, click "bugs bugs bugs"
b) click "new issue"
c) enter sev, status, summary
d) click ok
error (sorry, won't let me cut and paste text)
![image](https://f.cloud.github.com/assets/1028592/178460/c8618e56-7bb9-11e2-8210-2f28d77a04c8.png)

try the above again, but this time click "add" in the comment section after step #c. 
receive the following issue.

Thanks,
Bill

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'Interop.MSHTML, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Interop.MSHTML, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'
   at BEurtle.IssueDetail.TurnOnCommentEditing()
   at BEurtle.IssueDetail.CommentAdd_Click(Object sender, EventArgs e) in g:\BEurtle\BEurtle\IssueDetail.cs:line 839
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6400 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll

BEurtle
    Assembly Version: 1.5.0.1
    Win32 Version: 1.5.0.1
##     CodeBase: file:///C:/Program%20Files/ned%20Productions%20Limited/BEurtle/BEurtle.dll

System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6402 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6387 (Win8RTM.050727-6300)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
##     CodeBase: file:///C:/Windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by ned14** [comment]
Can you try completely uninstalling it, then check C:\Program Files\ned Productions Limited to make sure it's empty, then install it again? Thanks.

**Comment by billehunt** [comment]
Thanks for the fast reply. I tried clean install, but get the same result.
Also tried deleting the originally created .be dir with no success.

**Comment by ned14** [comment]
Ok, try opening a command box and then:

mkdir foo
cd foo
git init
"C:\Program Files\ned Productions Limited\BEurtle\dist\be" init
"C:\Program Files\ned Productions Limited\BEurtle\dist\be" new "I am a teapot short and stout"

... and see what happens.

**Comment by billehunt** [comment]
Sorry! The issue was that in Tortoise Git -> Settings -> Issue Tracker
Integration -> Settings -> Working Tree Path, I had entered the path to a
different repository. Entering the correct path resolves the issue.

However, this brings up another issue: Can BEurtle only be used with one
repository?

Also, do I understand the bug creation workflow is? Tortoise Git -> Commit
-> Bugs Bugs Bugs -> New Issue -> (info) -> Ok -> Ok -> Cancel -> Tortoise
Git -> Commit -> (repeat info) -> (select new bug files to commit and
unselect work files) -> OK
If so, very complex, I'm afraid. And worse than complex, it requires 10+
mouse clicks (I'd prefer zero). Or is there an easier process?

Thanks!

**Comment by ned14** [comment]
Just enter as many paths as is necessary to whichever GIT or other SVN repos you have in Tortoise, choosing BEurtle as the bug integration. It all just works nicely.

Regarding the bug creation workflow, you are right that going through Tortoise to create bugs is fiddly. However, that's Tortoise's fault, and I can't do much about it. What I have done though is create a small executable called BEgui.exe at C:\Program Files\ned Productions Limited\BEurtle\BEgui.exe. If you run that with the current directory set to some path e.g. via a shortcut, or a batch file, or a command box, it will search every directory above that current directory for a .be folder and launch BEurtle standalone on that repo.

You can also add C:\Program Files\ned Productions Limited\BEurtle\dist to your system PATH variable and simply type 'be gui' in a command box to directly enter BEurtle.

Hope this helps.

Niall
