### ISSUE TITLE
System.IO.FileNotFoundException: Interop.MSHTML not found

### ISSUE THREAD

**Issue by AxelAtS** [ned14/BEurtle#6]
Just started using BEurtle, but got trouble:

Windows 7 Pro
TortoiseGit 1.8.12.0 (C:\Program Files\TortoiseGit\bin) 
git version 1.9.4.msysgit.2 (C:\Program Files (x86)\Git\bin) 
BeUrtle 1.50 alpha 2, installed by the msi-Installer

Start BeUrtle GUI (doesn't matter which way) >
Path/URL: my Repository root (.be-folder already exists; was created when setting up TortoiseGit) >
Click New Issue >
Commentary: Click New >
Error message pop-up:

...
*************\* Ausnahmetext **************
System.IO.FileNotFoundException: Die Datei oder Assembly "Interop.MSHTML, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
Dateiname: "Interop.MSHTML, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null"
   bei BEurtle.IssueDetail.TurnOnCommentEditing()
   bei BEurtle.IssueDetail.CommentAdd_Click(Object sender, EventArgs e) in g:\BEurtle\BEurtle\IssueDetail.cs:Zeile 839.
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Protokollierung der Assemblybindung ist AUS.
Sie können die Protokollierung der Assemblybindungsfehler aktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) auf 1 festlegen.
Hinweis: Die Protokollierung der Assemblybindungsfehler führt zu einer gewissen Leistungseinbuße.
Sie können dieses Feature deaktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] entfernen.

*************\* Geladene Assemblys **************
mscorlib
    Assembly-Version: 2.0.0.0.
    Win32-Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400).
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll.

BEurtle
    Assembly-Version: 1.5.0.1.
    Win32-Version: 1.5.0.1.
##     CodeBase: file:///C:/Program%20Files/ned%20Productions%20Limited/BEurtle/BEurtle.dll.

System.Windows.Forms
    Assembly-Version: 2.0.0.0.
    Win32-Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400).
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.

System
    Assembly-Version: 2.0.0.0.
    Win32-Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400).
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll.

System.Drawing
    Assembly-Version: 2.0.0.0.
    Win32-Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400).
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.

System.Configuration
    Assembly-Version: 2.0.0.0.
    Win32-Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400).
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.

System.Xml
    Assembly-Version: 2.0.0.0.
    Win32-Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400).
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll.

System.Windows.Forms.resources
    Assembly-Version: 2.0.0.0.
    Win32-Version: 2.0.50727.5420 (Win7SP1.050727-5400).
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.

Microsoft.mshtml
    Assembly-Version: 7.0.3300.0.
    Win32-Version: 7.0.3300.0.
##     CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll.

mscorlib.resources
    Assembly-Version: 2.0.0.0.
    Win32-Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400).
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll.

*************\* JIT-Debuggen **************
...

PROCESSVIEWER tells several times:  Interop.MSHTML.dll","PATH NOT FOUND" :

"TortoiseGitProc.exe","ReadFile","C:\Windows\System32\mshtml.dll","SUCCESS","Offset: 17.981.440, Length: 16.384, I/O Flags: Non-cached, Pag...
"TortoiseGitProc.exe","ReadFile","C:\Windows\System32\mshtml.dll","SUCCESS","Offset: 17.965.056, Length: 16.384, I/O Flags: Non-cached, Pag...
"TortoiseGitProc.exe","CreateFile","C:\Program Files\TortoiseGit\bin\Interop.MSHTML.dll","NAME NOT FOUND","Desired Access: Read Attributes,...
"TortoiseGitProc.exe","CreateFile","C:\Program Files\TortoiseGit\bin\Interop.MSHTML\Interop.MSHTML.dll","PATH NOT FOUND","Desired Access: R...
"TortoiseGitProc.exe","CreateFile","C:\Program Files\TortoiseGit\bin\Interop.MSHTML.exe","NAME NOT FOUND","Desired Access: Read Attributes,...
"TortoiseGitProc.exe","CreateFile","C:\Program Files\TortoiseGit\bin\Interop.MSHTML\Interop.MSHTML.exe","PATH NOT FOUND","Desired Access: R...
"TortoiseGitProc.exe","CreateFile","C:\Program Files\ned Productions Limited\BEurtle\Interop.MSHTML.dll","NAME NOT FOUND","Desired Access: ...
"TortoiseGitProc.exe","CreateFile","C:\Program Files\ned Productions Limited\BEurtle\Interop.MSHTML\Interop.MSHTML.dll","PATH NOT FOUND","D...
"TortoiseGitProc.exe","CreateFile","C:\Program Files\ned Productions Limited\BEurtle\Interop.MSHTML.exe","NAME NOT FOUND","Desired Access: ...
"TortoiseGitProc.exe","CreateFile","C:\Program Files\ned Productions Limited\BEurtle\Interop.MSHTML\Interop.MSHTML.exe","PATH NOT FOUND","D...
"TortoiseGitProc.exe","CreateFile","C:\WINDOWS\assembly\GAC_64\mscorlib.resources\2.0.0.0_de-DE_b77a5c561934e089","PATH NOT FOUND","Desired...
"TortoiseGitProc.exe","CreateFile","C:\Windows\assembly\GAC_MSIL\mscorlib.resources\2.0.0.0_de-DE_b77a5c561934e089","NAME NOT FOUND","Desir...
"TortoiseGitProc.exe","CreateFile","C:\WINDOWS\assembly\GAC\mscorlib.resources\2.0.0.0_de-DE_b77a5c561934e089","PATH NOT FOUND","Desired Ac...
"TortoiseGitProc.exe","CreateFile","C:\Program Files\TortoiseGit\bin\de-DE\mscorlib.resources.dll","PATH NOT FOUND","Desired Access: Read A...
"TortoiseGitProc.exe","CreateFile","C:\Program Files\TortoiseGit\bin\de-DE\mscorlib.resources\mscorlib.resources.dll","PATH NOT FOUND","Des...
"TortoiseGitProc.exe","CreateFile","C:\Program Files\TortoiseGit\bin\de-DE\mscorlib.resources.exe","PATH NOT FOUND","Desired Access: Read A...
"TortoiseGitProc.exe","CreateFile","C:\Program Files\TortoiseGit\bin\de-DE\mscorlib.resources\mscorlib.resources.exe","PATH NOT FOUND","Des...
"TortoiseGitProc.exe","CreateFile","C:\WINDOWS\assembly\GAC_64\mscorlib.resources\2.0.0.0_de_b77a5c561934e089","PATH NOT FOUND","Desired Ac...
"TortoiseGitProc.exe","CreateFile","C:\Windows\assembly\GAC_MSIL\mscorlib.resources\2.0.0.0_de_b77a5c561934e089","SUCCESS","Desired Access:...
"TortoiseGitProc.exe","QueryBasicInformationFile","C:\Windows\assembly\GAC_MSIL\mscorlib.resources\2.0.0.0_de_b77a5c561934e089","SUCCESS","...

I tried several things (deinstall/reinstall etc., disable all options of BEurtle), but without success.

Axel

**Comment by AxelAtS** [comment]
From what I read, maybe it is related to the version of mshtml.dll. This dll seems to get updated by an Internet Explorer update, which is IE10 on my side.

Axel

**Comment by ned14** [comment]
The reason I haven't replied is because I haven't got round to setting up a virtual machine to test this. The usual cause of this error is when something has deleted the mshtml file but not updated the registry to say so. This is depressingly common unfortunately, but it is possible that an IE update broke it and until I test it with a newly installed Windows I can't say. You can in the meantime try manually installing mshtml  using https://github.com/ned14/BEurtle/blob/master/Installer/Redist/vs_piaredist.exe and see what happens, though it too may think mshtml is already installed. Let me know how that goes for you. Niall

**Comment by AxelAtS** [comment]
Unfortunately, same error (and same error message). I tried it with and without computer restart, with and without beurtle reinstall, and other variations.

**Comment by AxelAtS** [comment]
Hi Niall,

I can’t get it working, see last reply here:
https://github.com/ned14/BEurtle/issues/6

One more chance?


Kind Regards,
Axel

Von: Niall Douglas [mailto:notifications@github.com]
Gesendet: Sonntag, 18. Januar 2015 13:29
An: ned14/BEurtle
Cc: Friedrich, Axel
Betreff: Re: [BEurtle] System.IO.FileNotFoundException: Interop.MSHTML not found (#6)


The reason I haven't replied is because I haven't got round to setting up a virtual machine to test this. The usual cause of this error is when something has deleted the mshtml file but not updated the registry to say so. This is depressingly common unfortunately, but it is possible that an IE update broke it and until I test it with a newly installed Windows I can't say. You can in the meantime try manually installing mshtml using https://github.com/ned14/BEurtle/blob/master/Installer/Redist/vs_piaredist.exe and see what happens, though it too may think mshtml is already installed. Let me know how that goes for you. Niall

**Comment by ned14** [comment]
Thanks for reminding me about this. It looks like Microsoft arbitrarily broke MSHTML for some reason, but all I had to do here was to remove the import and readd it and recompile. I'm just waiting now for a new installer signing certificate and then I'll push an updated installer. Thanks for the patience.

**Comment by ned14** [comment]
Try the alpha 3 installer at http://dedi3.nedprod.com/static/files/. Uninstall the old BEurtle first. I'm just about to leave for a week of vacation, so I may not be able to reply until next weekend. Hope it now works for you.

**Comment by AxelAtS** [comment]
When switching off bexml-caching, alpha 3 seems to work! - I'll use it now and report my experience.

**Comment by AxelAtS** [comment]
Closed it without intention - Sorry.

**Comment by ned14** [comment]
How's it faring for you?

**Comment by AxelAtS** [comment]
It's working well now. Still have to have switched off "bexml-caching", but that's no problem for me. (Caching seems to access a wrong directory.) - In my opinion, this issue can be closed now. - Thank you!

**Comment by ned14** [comment]
Thanks for reporting the problem!
